# Colors (Green)
[window]
opacity = 1

[font]
size = 9
normal = { family = "VHS Gothic", style = "Regular" } 
#normal = { family = "VT323", style = "Regular" } 

# Default colors
[colors.primary]
background = '#000000'
foreground = '#ffbf00'

# Colors the cursor will use if `custom_cursor_colors` is true
[colors.cursor]
text = '#000000'
cursor = '#ffbf00'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#ffbf00'
green   = '#d07317'
yellow  = '#ffd900'
blue    = '#dd8800'
magenta = '#ff8800'
cyan    = '#bc7628'
white   = '#905000'

# Bright colors
[colors.bright]
black   = '#444444'
red     = '#ffbf00'
green   = '#d07317'
yellow  = '#ffd900'
blue    = '#dd8800'
magenta = '#ff8800'
cyan    = '#bc7628'
white   = '#905000'
